version: '3'

services:
  namespace:
    restart: unless-stopped
    build: ./namespace
    ports:
      - "3000:3000"

  
  ipfs:
    image: ipfs/kubo
    restart: unless-stopped
    volumes:
      - ./ipfs_config:/data/ipfs
      - ./client/frontend:/data/chatit
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"

  psql:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_USER: locallookup
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chatit
    volumes:
      - data:/var/lib/postgresql/data
      - ./hosts/init.sql:/docker-entrypoint-initdb.d/init.sql

  hosts:
    restart: unless-stopped
    build: ./hosts
    ports:
      - "5000:5000"
    links:
      - psql
      - namespace
    depends_on:
      - psql
      - namespace

volumes:
  data:
