# Use the official Go image as the base image
FROM golang:1.19.2-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the go.mod and go.sum files to the container
COPY go.mod ./

# Install the dependencies
RUN go mod download

# Copy the rest of the application files to the container
COPY . .

# Build the application
RUN go build -o main .

# Expose port 8080 for the application to listen on
EXPOSE 8080

# Start the application
CMD [ "./main" ]
